DROP TABLE IF EXISTS bbd_user;
CREATE TABLE `bbd_user` (
  `id` BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `gmt_create` DATETIME DEFAULT NULL COMMENT '创建时间',
  `gmt_modified` DATETIME DEFAULT NULL COMMENT '修改时间',
  UNIQUE(username)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS bbd_account;
CREATE TABLE `bbd_account` (
  `id` BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(64) DEFAULT NULL,
  `phone` VARCHAR(16) DEFAULT NULL,
  `email` VARCHAR(64) DEFAULT NULL,
  `region` VARCHAR(16) DEFAULT NULL,
  `dep_note` VARCHAR(64) DEFAULT NULL,
  `gmt_create` DATETIME DEFAULT NULL COMMENT '创建时间',
  `gmt_modified` DATETIME DEFAULT NULL COMMENT '修改时间',
  UNIQUE(user_id)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='账户表';
